flags: {}
packages:
- '.'
local-bin-path: dist
# When you have extra deps, it's nice to bake them into the snapshot.
# This means for example you can have a base image with extra deps included.
# It is also more portable between machines (and host vs docker).
resolver: custom-snapshot.yaml
